name: CI/CD Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Check formatting
        run: poetry run black --check .

      - name: Run tests
        run: poetry run pytest pygraph.py --cov=pygraph

      - name: Generate docs
        run: poetry run pdoc --html pygraph -o html/pygraph

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: html/pygraph
          token: ${{ secrets.GH_PAGES_TOKEN }}
          clean: true
